### ISSUE TITLE
[suggestion] Latex format?

### ISSUE THREAD

**Issue by briochemc** [PainterQubits/Unitful.jl#167]
Is there a printing function or macro that is readable as a LaTeX string? E.g., something like
```julia
julia> α = 3u"m/s"
3 m s^-1

julia> latexify(α)
L"3\,mathrm{m}\,\mathrm{s}^{-1}"
```
where the important details are
- the `\,` spaces between value and units (and between units),
- the `\mathrm` commands to make sure the unit symbols are upright and not in "math-mode",
- and the exponents are inside brackets because LaTeX does not give precedence to the entire exponent — and would print only the first character (the `-`, minus) as an exponent (instead of the full `-1` exponent in the example above).

**Comment by JMurph2015** [comment]
I would also appreciate some integration with Latex, mainly so I can pretty print them in notebooks.  Currently I have handful of custom shims for a `latex()` method for things like arrays of Syms from SymPy, but have yet to figure out a shim for Unitful.

**Comment by briochemc** [comment]
just in case this helps, I currently write my own function to print values with units.
```julia
Using Unitful

function latexify(U)
    str = string(U)
    str = replace(str, r"\^-(?<exp>\d+)" => s"$^{-\g<exp>}$") # add brackets around exponents
    str = replace(str, r"\s" => s"\\,") # replace spaces with small spaces
    return str
end
```
and I use at the REPL so that 
```julia
julia> a = 3u"m*s^-2"
3 m s^-2

julia> println(latexify(a))
3\,m\,s$^{-2}$
```
It's not what I originally described but it gives me what I want: I just copy whatever the REPL outputs (`3\,m\,s$^{-2}$` in this case) and paste it into a LaTeX file or table or whatever you need. Hope this helps!

**Comment by spatil47** [comment]
It would be nice if it could use the siunitx package (https://ctan.org/pkg/siunitx).

**Comment by briochemc** [comment]
> It would be nice if it could use the siunitx package (https://ctan.org/pkg/siunitx).

Yes, but keep in mind that some (most?) journals don't accept that you add your own packages, and if they don't have siunitx, then you'd rather have a plain LaTeX solution IMHO.

**Comment by gustaphe** [comment]
> It would be nice if it could use the siunitx package (https://ctan.org/pkg/siunitx).

I wanted this functionality as part of a pet project (not quite ready to make it a real package or contribution yet), but I thought you might like to know this actually turned out to be pretty okay/simple, because `Unit` objects have a `name` parameter. I'm sure there are plenty of cases where this breaks down, but this would probably be a serviceable start if someone wanted to implement this. 

```julia
function printdata(f::IO,v::Unitful.Quantity)
    print(f,"\\SI{$(v.val)}{")
    siunitxprint(f,Unitful.unit(v))
    print(f,"}")
end
```

```julia
function siunitxprint(f::IO,u::Unitful.FreeUnits)
    prefixes = Dict(
                          -24 => "\\yocto",
                          -21 => "\\zepto",
                          -18 => "\\atto",
                          -15 => "\\femto",
                          -12 => "\\pico",
                          -9  => "\\nano",
                          -6  => "\\micro",
                          -3  => "\\milli",
                          -2  => "\\centi",
                          -1  => "\\deci",
                          0   => "",
                          1   => "\\deka",
                          2   => "\\hecto",
                          3   => "\\kilo",
                          6   => "\\mega",
                          9   => "\\giga",
                          12  => "\\tera",
                          15  => "\\peta",
                          18  => "\\exa",
                          21  => "\\zetta",
                          24  => "\\yotta"
                         )
    for p in typeof(u).parameters[1]
        p.power<0 && print(f,"\\per")
        iszero(p.tens) || print(f,prefixes[p.tens])
        print(f,"\\$(lowercase(String(Unitful.name(p))))")
        abs(p.power)==1 || print(f,"\\tothe$(Int64(abs(p.power)))")
    end
end
```

Having previously written a similar function in Matlab, I'm even deeper in love with Julia right now than before.

**Comment by gustaphe** [comment]
In the service of self-promotion:
```julia
julia> using Unitful, Latexify, UnitfulLatexify; # this last one is new
julia> latexify(24u"km")
L"$24\;\mathrm{km}$"
julia> latexify(24u"km",unitformat=:siunitx)
L"\SI{25}{\kilo\meter}"
```

**Comment by briochemc** [comment]
Nice! You should link to it and announce it on discourse!

**Comment by NightMachinary** [comment]
[**@gustaphe**](https://github.com/gustaphe) commented on [Jan 28, 2021, 1:50 AM GMT+3:30](https://github.com/PainterQubits/Unitful.jl/issues/167#issuecomment-768616598 "2021-01-27T22:20:01Z - Replied by Github Reply Comments"):
> In the service of self-promotion:
> 
> ```julia
> julia> using Unitful, Latexify, UnitfulLatexify; # this last one is new
> julia> latexify(24u"km")
> L"$24\;\mathrm{km}$"
> julia> latexify(24u"km",unitformat=:siunitx)
> L"\SI{24}{\kilo\meter}"
> ```

Is this viewable on VSCode's REPL?

**Comment by gustaphe** [comment]
I haven't used VSCode, so I don't know, but if LaTeXStrings strings (i.e. L"x") are, then so are Latexify-cations, including these. If you can't tell it to `\usepackage{siunitx}` you will need to stick to `unitformat=:mathrm` (the default), but it will work.

**Comment by giordano** [comment]
I think this issue can be closed now?

**Comment by sheerun** [comment]
@gustaphe Can you format measurements to something like `6.674(15)` i.e. put uncertainty in parenthesis?

**Comment by gustaphe** [comment]
If whatever package you use to represent that uncertainty  (Measurements.jl?) implements a `latexrecipe` then yes. If it doesn't, that sounds like a good pull request.
