### ISSUE TITLE
Better display for units

### ISSUE THREAD

**Issue by ajkeller34** [PainterQubits/Unitful.jl#18]
[SIUnits.jl](https://github.com/Keno/SIUnits.jl) seemed to handle this pretty well. There's no superscript slash in Unicode, so printing rational exponents using Unicode only will be problematic.

**Comment by mlhetland** [comment]
I see this is closed, but I thought I wouldn't open a new issue just for this: Might it be a good idea to differentiate between compact and non-compact display? Primarily removing the space in compact display, I guess, so `show(1cm)` gives you `1 cm` but `showcompact` yields `1cm`? (Similar to operator spacing for complex numbers, for example.)
