### ISSUE TITLE
Unitful ranges are really hard to read

### ISSUE THREAD

**Issue by c42f** [PainterQubits/Unitful.jl#199]
I have to squint extra hard to read the following, and it comes up a lot when using ranges as time axes with `AxisArrays`:

```julia
julia> (1:10)u"s"
1 s:1 s:10 s
```

Is there anything we can realistically do about this? It is, of course, possible to define something ugly like

```julia
Base.show(io::IO, r::AbstractRange{<:Quantity}) = print(io, repr(first(r)), " : ", repr(step(r)), " : ", repr(last(r)))
```

I'm not sure whether this would constitute type piracy or whether it would be ok.

**Comment by ajkeller34** [comment]
I don't think it counts as type piracy since the type of `r` couldn't exist without this package. I'm not completely confident that all abstract ranges display that way though. Unit ranges would be an obvious exception, but those aren't supported by / don't make sense for quantities anyway.

**Comment by c42f** [comment]
Yes, I currently can't think of any problems which could occur by defining `show` like this.

In terms of presentation, I thought another option would be to remove the whitespace from between the number and the unit. This would be more compact and consistent with normal range printing, but less consistent with the display of units elsewhere and doesn't really help for more complex units

```
1 s:1 s:10 s

1 s : 1 s : 10 s

1s:1s:10s
```

```
0 m s^-1:1 m s^-1:100 m s^-1

0 m s^-1 : 1 m s^-1 : 100 m s^-1

0m s^-1:1m s^-1:100m s^-1
```

**Comment by ajkeller34** [comment]
What about defining a few methods of `show` for concrete subtypes of `AbstractRange` in addition to the `AbstractRange` fallback? It would reduce visual clutter to display ranges as `(1:1:10)s` instead of `1 s:1 s:10 s` when the step has the same units as the start and stop, for instance.
