### ISSUE TITLE
Add function for run-time parsing

### ISSUE THREAD

**Issue by alhirzel** [PainterQubits/Unitful.jl#214]
The `@u_str` macro is useful when units are known in advance. In some cases, however, units must be determined at runtime. This requires parsing strings as numeric and Unitful values, which is currently sort of ugly:

```julia
val, unit = split(rawValue, " "; limit=2)
return parse(Float64, val)*(@eval @u_str $unit) # ugly
```
I'd like to propose that Unitful include a function which exposes this kind of behavior (i.e. parse quantity from string). It would be good if it were resilient to having a space (or not) between the numeric and the unit.

**Comment by tlnagy** [comment]
I use `Unitful` in `OMETIFF.jl` and I annotate the axes with units, but I don't know the units beforehand so I have to something like this:
```julia
unittype = getfield(Unitful, Symbol(image["TimeIncrementUnit"])) # ugly hack
```

at runtime. It would be great to have a better, sanctioned way of doing this.

**Comment by c42f** [comment]
I just ran into this with regards to deserilaizing unit strings from a file. I do think we should have a better story for unit string (de)serialization.

It should be fairly easy to implement by processing the output of `replace_value(context_module, Meta.parse(str))` to evaluate the limited set of allowed functions in the resulting `Expr`. But there's a few wrinkles:
* What do we do about unit extension modules? This is currently dealt with by the macro inferring  `context_module` to be the current module, and using that to infer the set of "active unit extension modules". But the logic for this is a bit convoluted and confusing (cf. #272 for example). For a runtime version it might be better just to have the user explicitly pass the allowed set of extension modules (with `Unitful` being the default).
* What about security in parsing unknown strings? `Meta.parse` itself is safe in principle, but `replace_value` looks up arbitrary symbols in the unit definition modules which seems a little iffy. Maybe it would be sensible to restrict the type of such lookups with an extra check.

**Comment by Datseris** [comment]
Just chiming in to say that we want something exactly like this in NCDatasets, for JuliaGeo/JuliaEarth/JuliaClimate. Actually we have the units as a separate string like "W m-2" and we'd like to use that string to make numeric arrays Unitful arrays. Seems that the only way to do this is at the moment is `(@eval @u_str $unit)`, with `unit` our string, but I was expecting a normal and well tested function like `tounit(str)`. It would lead to a more robust ecosystem if this had more support.

**Comment by c42f** [comment]
What's the format of your unit strings? If they're not julia syntax (as your example "W m-2" seems not to be) then `u_str` won't be able to parse them currently. 

What is the desired format for serializing unit strings in general? Currently it's julia syntax which seems like a sensible default for interactive work. But it would also "be nice" to support a cross-language standard for unit strings if a suitable one exists.

I did some research but couldn't find a really obvious consensus. Some things I did find:

* The [NIST SP811](https://www.nist.gov/pml/special-publication-811/nist-guide-si-chapter-6-rules-and-style-conventions-printing-and-using) is influential but doesn't specify a precise grammar for unit strings.
* The [FITS standard](https://fits.gsfc.nasa.gov/standard40/fits_standard40aa-le.pdf) is well developed but "overcomplete" allowing flexible parsing of various non-unique representations of a unit string. It's the standard followed in the [astropy.units](https://docs.astropy.org/en/stable/units/format.html#converting-units-to-string-representations) library and seems to have inspired various other standards and proto-standards such as ASDF which defers to FITS.
* The [MIXF standard](https://people.csail.mit.edu/jaffer/MIXF/MIXF-10) seems to be an elaborated version of SP811 for plain text unit strings provides a formal grammar. This seems promising but is rather opinionated about using `.` as multiplication which means incompatibility with julia syntax.
* The NetCDF format appears to use the udunits package which has a unit parser with [a grammar](https://www.unidata.ucar.edu/software/udunits/udunits-current/doc/udunits/udunits2lib.html#Syntax) also derived from SP811 with an extension for affine units.
* The python [pint library](https://pint.readthedocs.io/en/0.10.1/tutorial.html#sec-string-formatting) seems to use python syntax for unit string constructions

The example "W m-2" appears to follow the FITS standard which interprets `m-2` to be `m^(-2)`.

**Comment by Datseris** [comment]
Yeap, in my case "W m-2" means Watt per meter squared. Well this function I am asking here should definitely make at least some standard things like interpreting all numbers as exponents of the previous symbol and also taking into account white space. 

Searching for a super duper general standard might not even be feasible as different fields may write something differently. Having a starting point function from Unitful.jl that takes in a string and makes it a unit is good. Then we can improve it as time progresses, or if something is too specific for a specific package like e.g. NCDatasets.jl, the string can be first converted to a more appripriate form in the specialized package and then passed into Unitful.jl.

**Comment by c42f** [comment]
> at least some standard things like interpreting all numbers as exponents

To be honest I found this quite surprising behavior! It's inconsistent with the way `u_str` currently works. Not to say it's bad or wrong; it appears to be a standard thing for FITS which allows several different representations for exponents. But I think it shows that there can be some subtlety even for "obvious" parsing behaviors.

As a baseline, I'd suggest we just implement the current `u_str` behavior as a function.

**Comment by c42f** [comment]
I implemented a baseline version of this in #298

**Comment by Datseris** [comment]
> To be honest I found this quite surprising behavior!

Just so that we are clear, you found surprising that all numbers are exponents in a unit string? Because you would expect that `^` must always be explicitly stated?

**Comment by c42f** [comment]
> Because you would expect that ^ must always be explicitly stated?

Yes.

In fact, `u_str` currently uses normal julia parsing rules, so `u"m2"` is looked up as a unit with the symbolic name `:m2` in any of the unit extension modules. (No judgement implied about whether that's the ideal behavior, but that's what happens currently.)

**Comment by Datseris** [comment]
But since we are talking about _units_, which don't have a numeric value and therefore it does not make sense to multiply them by a number, wouldn't you agree that it seems more reasonable to interpret numbers as exponents? Like, the default behavior? 

I am more surprised than you were initially that this is not the default behavior :P

**Comment by c42f** [comment]
> wouldn't you agree that it seems more reasonable to interpret numbers as exponents

Perhaps. But of course `m2` is a valid julia variable name. `Unitful` gives package authors freedom to name their custom units as they wish, according to the usual rules for constructing valid Julia identifiers. So I think there's quite a tension between `m2` being a julia identifier, and your desire for "m2" to be parsed as `m^2`

**Comment by Datseris** [comment]
You have a good point that I didn't consider. So therefore I want to write a custom formatting function that does what I find "intuitive" formatting at a string and then gives it to `parseunit`.

**Comment by c42f** [comment]
To be honest I feel like string munging prior to `parseunit` is unlikely to work robustly for all edge cases. As I said at https://github.com/PainterQubits/Unitful.jl/pull/298#issuecomment-575562368, you may need a custom NetCDF-specific parser to really get it right.

**Comment by briochemc** [comment]
What's the inverse of `uparse`? I.e., something such that we can easily convert to standard strings and back?
```julia
x = 3.0u"m s"
str = uparse_inverse(x) # looking for such a function
x == uparse(str) # such that this is true
```

**Comment by rafaqz** [comment]
For some context on @briochemc 's question - the early WIP https://github.com/rafaqz/ModelParameters.jl has a Tables.jl interfaces and also facilitates using Unitful.jl `units` fields - so saving the units column to CSV, and loading it again to rebuild the model is a natural outcome of that potential.

But currently it's not clear if we can do two-way serialization/deserialisation of units to strings and back cleanly - for writing tables to csv - as `uparse(string(u"m*s"))` doesn't work!

 But it would be amazing if we could, and likely useful in other packages as well. Does this simple reuqire parsing whitespace as `*`?

**Comment by c42f** [comment]
In principle, perhaps it should be `show(io, u)`, as that's meant to write the decorated text representation, while `print` is meant for the undecorated form.  Thus `print`/`string` would continue to function as they do currently, while `show` would produce valid Julia syntax? To quote the `print` documentation:

>   print([io::IO], xs...)
>
>  Write to io (or to the default output stream stdout if io is not given) a canonical (un-decorated) text representation. The representation used by print includes minimal formatting and tries to avoid Julia-specific details.
>
>  print falls back to calling show, so most types should just define show. Define print if your type has a separate "plain" representation. For example, show displays strings with quotes, and print displays strings without quotes.

To prevent this from being too awful in interactive use, we could additionally define `show(::IO, ::MIME"text/plain", unit)` to use the undecorated form; this is the MIME type that the REPL uses.

**Comment by rafaqz** [comment]
That makes sense. One concern with that is other uses of `show` and specifically tables with units columns where people want the undecorated version. Currently, if we build a dataframe with a column of units:

```julia
using DataFrames, Unitful, CSV

df = DataFrame(units=[u"m*s^2", u"K", u"K*Pa^-1"])
CSV.write("uints.csv", df)
```

The resulting csv is in the spaces between units form:
```
units
m s^2
K
K Pa^-1
```

From a quick scan it appears that CSV.jl uses `show` (although I don't really know the codebase) - so in this proposal updating `show` to output the pure julia representation would change this behavior, and the full julia code would be present in the table above.

One issue with that approach would be that any table you make with units would then have the `*` all through it, which is probably not what people want if they are e.g. using Weave.jl to generate parameter tables in their reproducible papers.

Solutions I can think of for this are to just parse whitespace as `*` in `uparse`, or to inform people to use `string.(units)` on their units column if they want the current string representation in their table.

**Comment by c42f** [comment]
> to inform people to use `string.(unitscolumn)` on their units column if they want the current string representation in their table.

I think this would be pretty ok actually. But it's true that it would be a breaking change for some users.

**Comment by rafaqz** [comment]
Ok. So in terms of a PR this would involve:

- [ ] swapping current `show` methods to work with `print`
- [ ] write new show methods that return the raw julia version
- [ ] write some tests for print/string/show behaviours
