### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by m-wells** [PainterQubits/Unitful.jl#219]
In the documentation:
> # `Unitful.uconvertp` — *Function*.
> ```julia
> uconvertp(u::Units, x)
> uconvertp(u::MixedUnits, x)
> ```
> Generically, this is the same as `Unitful.uconvert`. In cases where unit conversion would be ambiguous without further information (e.g. `uconvert(dB, 10)`), **`uconvertp` presumes ratios are of root-power quantities**.
> ...
> ...
> # `Unitful.uconvertrp` — *Function*.
> ```julia
> uconvertrp(u::Units, x)
> uconvertrp(u::MixedUnits, x)
> ```
> In most cases, this is the same as `Unitful.uconvert`. In cases where unit conversion would be ambiguous without further information (e.g. `uconvert(dB, 10)`), **`uconvertp` presumes ratios are of power quantities**.

I have put the issues in bold.  I believe the first instance should be changed to
```julia
`uconvertp` presumes ratios are of power quantities
```
and the second one should be changed to
```julia
`uconvertrp` presumes ratios are of root-power quantities
```

**Comment by treygreer** [comment]
I agree!  This documentation error caused me a bit of pain...  I'm happy to implement this fix and do a pull request, if someone more familiar with the package could first chime in and agree.
