### ISSUE TITLE
Dealing with Real and Complex Quantities

### ISSUE THREAD

**Issue by steinQF** [PainterQubits/Unitful.jl#223]
It's tempting to think only real quantities matter, e.g. an imaginary meter would be strange and unphysical. In fact, generalized frequencies can be complex. Gaussian beam propagation using the [Ray Transfer Matrix](https://en.wikipedia.org/wiki/Ray_transfer_matrix_analysis) approach is another example where there are complex but unitful quantities involved.

I'm trying to generalize code for Gaussian beam propagation using Ray Transfer Matrices ([Issue 6 on ABCDBeamTrace.jl](https://github.com/ngedwin98/ABCDBeamTrace.jl/issues/6) in particular) written using dimensionless `Real` and `Complex` (with implied units) such that it works with Unitful.

Does anyone have suggestions for how to deal with the problem that Unitful.Quantity is merely a number and neither a subtype of `Real` or a `Complex`?

I think it would make sense to define at least a `Base.complex(realpart::Unitful.AbstractQuantity, imagpart::Unitful.AbstractQuantity=zero(realpart))` to ease defining complex, unitful quantities based on real valued ones. Ideally, I'd obviously wish for a Unitful.Quantity that somehow subtypes `Real` or `Complex` depending on the underlying type.

Would it make sense to define `AbstractQuantity` to be a subtype of `Real` and have `Complex{AbstractQuantity}` allowed? I'm not quite sure about that, since unitful quantities aren't strictly Real numbers, but it would lead to more code reuseability.

I realize there was an earlier discussion about subtyping, #197 and #9, and if I understand correctly, the verdict was that `Unitful.Quantity` should not subtype `Real` or `Complex`. I'm not sure I agree, but if that's the route to go, then how should one handle migrating code that tries to stay generic yet would benefit from being able to handle Unitful numbers?

**Comment by giordano** [comment]
I second this proposal, but I think it has been already rejected in the past.

**Comment by steinQF** [comment]
`Base.complex` is, of course, not the only method I'd need. The addition of `Base.real` and `Base.imag` should suffice for me, but obviously there is more to doing this properly (e.g. `Base.conj`). And that's assuming that code using this can be changed into using `::Number` instead of `::Real` and `::Complex`...

Are there any better ideas for solving this problem?

**Comment by steinQF** [comment]
In starting to implement this in https://github.com/Quantum-Factory/Unitful.jl/tree/qf-complex, I noticed that most methods (like `real`, `imag` and `conj`) are already implemented, so this issue is mostly about `Base.complex` (and a few missing methods such as `widen` that are not really specific to complex numbers).

**Comment by steinQF** [comment]
There is a PR #227 that adds missing methods for complex, unitful quantities, open and passing tests since 20 days ago. Can it be merged, @ajkeller34 ?

Thanks alot for this useful package, btw!

**Comment by ajkeller34** [comment]
Please see #228. I'm sorry for the delay, but it seems likely I will be able to continue maintaining a fork of this package very soon, which is a pretty good outcome, I think.

**Comment by ajkeller34** [comment]
I find Tim Holy's arguments in https://github.com/PainterQubits/Unitful.jl/issues/9#issuecomment-236252304 pretty compelling, so I remain against making `Quantity` types a subtype of `Real`. I'm more than happy to merge #227 after some comments I just left are addressed though! Thank you for the useful PR.
