### ISSUE TITLE
Bug: Array Division by Unit

### ISSUE THREAD

**Issue by bhgomes** [PainterQubits/Unitful.jl#225]
```julia
using Unitful
ones(3) / u"s"

ERROR: MethodError: no method matching /(::Array{Float64,1}, ::Unitful.FreeUnits{(s,),𝐓,nothing})
```

It appears that division by unit was not implemented here, just multiplication.

https://github.com/ajkeller34/Unitful.jl/blob/82f84969c2b78fcc3f66bc23ef997e81c0f0661e/src/quantities.jl#L35-L36

**Comment by sostock** [comment]
This was fixed in #369.
