### ISSUE TITLE
Move Unitful.jl to an organisation?

### ISSUE THREAD

**Issue by giordano** [PainterQubits/Unitful.jl#228]
Andrew seems to be not too responsive lately.  While this is understandable (this is a FOSS project, probably developed during spare time) and I don't want to put shame on anyone, this is holding development of the package from going on.  Pull requests are piling up, some of them should be relatively trivial to review.

I'd suggest to transfer the ownership of the package to an organisation where other selected people would have push rights.  In particular, I think that this package would perfectly fit within the scope of [`JuliaPhysics`](https://github.com/JuliaPhysics).  Comments?

**Comment by ajkeller34** [comment]
I am trying to determine if I am even allowed to merge pull requests given that this was developed at Caltech and I am no longer employed there. I would appreciate your patience on this matter and anticipate it to be resolved in a few weeks. The best outcome would be that I am able to maintain it as part of my job duties. I will update here.

**Comment by giordano** [comment]
> I am trying to determine if I am even allowed to merge pull requests given that this was developed at Caltech and I am no longer employed there. 

Thanks for the answer and the explanation!

> I would appreciate your patience on this matter and anticipate it to be resolved in a few weeks.

Sure, no rush, it's just that we didn't hear much from you in this project lately :slightly_smiling_face:

> The best outcome would be that I am able to maintain it as part of my job duties. I will update here.

:crossed_fingers:

**Comment by giordano** [comment]
> I am trying to determine if I am even allowed to merge pull requests given that this was developed at Caltech and I am no longer employed there.

However this point is not very clear to me: standing the current license, anyone is allowed to fork the repository and build on it, so why wouldn't you allowed to continue developing it?

**Comment by ajkeller34** [comment]
You are correct, anyone is allowed to fork this and build on it, but I agreed to assign my copyright to Caltech, and this original repository should be hosted by a Caltech-affiliated GitHub user or organization. I am working on moving it to such a place now (GitHub should auto-redirect), and will find out if there is interest from my former group in maintaining it. If not, are you able to maintain a fork? It would probably be cleanest if it weren't me.

**Comment by cstjean** [comment]
I wouldn't mind reviewing smaller PRs, but I barely have time to maintain my own packages, and I wouldn't claim to have the expertise to maintain all parts of this package adequately.  Hopefully @ajkeller34 can work things out.

**Comment by ajkeller34** [comment]
Just wanted to check in. A solution is in sight, so thank you for your continued patience!

**Comment by ajkeller34** [comment]
Update: I will maintain a fork of this package at https://github.com/rigetti/Unitful.jl, and will implement a PR to the Julia general registry to point to the fork. The fork has the same license terms, and Unitful won't be developed further in the PainterQubits org (I've discussed with org owners). I'll see if I can't get someone in my former group to help move issues and PRs over. As before, thanks for your patience.

**Comment by StefanKarpinski** [comment]
See https://github.com/JuliaRegistries/General/pull/1296#issuecomment-500449009:

---

> If they have no interest in maintaining, can't you just transfer the repo to your user again?

> No, I cannot, as I don't hold the copyright.

These are not related. The only thing copyright law requires in this case is that the MIT license file indicating that the project's copyright "California Institute of Technology and other contributors" be preserved in all copies, whether they are forks or not. GitHub's concept of transfer versus fork makes no legal difference. There is no legal requirement that the location of repo remain where it was, nor does where it is hosted have any relationship with who owns the copyright.

The only impediment to transferring the original Unitful.jl repo elsewhere is if the PainterQuibits organization is unwilling to do so. Is the head of the Painter Lab unwilling to transfer Unitful.jl to JuliaPhysics? That seems like the right home for it. Doing so would have no effect on the copyright and the LICENSE file would stay the same. It would also preserve the continuity of the issues and so on.

**Comment by ajkeller34** [comment]
After discussing further with all relevant parties, the new plan is to maintain Unitful here as an outside collaborator admin, which addresses concerns including retention of issue and pull request history, and is least disruptive for all involved. I had misunderstood the copyright issue due to some conflicting information from multiple people. Thank you to Stefan for some helpful discussion.

**Comment by c42f** [comment]
Awesome, thanks Andrew for sorting this out, this seems like a workable solution.

Just a small suggestion while this is fresh in people's minds: If the PainterQubits admins are agreeable, I would suggest they make you an owner of this one repo (not merely a collaborator) because that will make it possible for you to properly maintain several aspects of the project which I believe are closed to collaborators. For example, installing JuliaRegistrator and other github integrations as necessary.

**Comment by gihwan-scqubits** [comment]
Hello @giordano and @ajkeller34, I am Gihwan, the current admin of the PainterQubits organization. I just changed @giordano's  role in PainterQubits/Unitful.jl to admin. It is totally fine to move the Unitful.jl to JuliaPhysics. I tried to transfer ownership to @giordano, but there seems to be a collision of repository names (giordano/Unitful.jl exists). @giordano, If you would like the ownership to be transferred, please rename the forked version of Unitful. Thank you.

**Comment by giordano** [comment]
Awesome, thank you so much @gihwan-scqubits! 🎉 I moved it to https://github.com/JuliaPhysics/Unitful.jl

**Comment by icweaver** [comment]
Much appreciated, thank you all!
