### ISSUE TITLE
Doc links broken

### ISSUE THREAD

**Issue by braamvandyk** [PainterQubits/Unitful.jl#242]
All of the doc links lead to 404 errors.

**Comment by briochemc** [comment]
I think they know (https://github.com/PainterQubits/Unitful.jl/pull/230) but maintainer is busy? New link for docs is https://painterqubits.github.io/Unitful.jl/stable/.

**Comment by giordano** [comment]
> I think they know (#230) but maintainer is busy?

No: #228

**Comment by briochemc** [comment]
Oh I see — It might be good to indicate that at the top of the readme's of both [this repo](https://github.com/PainterQubits/Unitful.jl/blob/master/README.md) and the @ajkeller34 [one](https://github.com/PainterQubits/Unitful.jl/blob/master/README.md), right?

**Comment by ajkeller34** [comment]
I think everything is fine now, I've merged the doc link PRs and the repo will live here for the foreseeable future.

**Comment by briochemc** [comment]
But where should one go for docs/issues/code? In here or on the Rigetti fork?

**Comment by ajkeller34** [comment]
The Rigetti fork will not be used as it turns out I am able to be an admin of the original repo, which had been moved here. See https://github.com/PainterQubits/Unitful.jl/issues/228#issuecomment-500960333
