### ISSUE TITLE
Degree printing

### ISSUE THREAD

**Issue by bramtayl** [PainterQubits/Unitful.jl#253]
Something has changed in the way degrees are printed that causes my doctests to fail. See e.g. https://travis-ci.org/bramtayl/LightQuery.jl/jobs/555926202 . I think the old way is better?

**Comment by c42f** [comment]
It appears that the new style is correct in the sense that it's following the standard: https://physics.nist.gov/cuu/Units/checklist.html (see item 15)

However the following is inconsistent which is a bug:

```julia
julia> show(1u"°")
1°
julia> display(1u"°")
1 °
```

**Comment by bramtayl** [comment]
I already updated all my doctests so don't fix it!

**Comment by c42f** [comment]
Well the bug should be fixed by making `display` the same as `show`, not the other way around. So your doctests should be fine.
