### ISSUE TITLE
conversion from RPM to rad/s is incorrect

### ISSUE THREAD

**Issue by jordancluts** [PainterQubits/Unitful.jl#261]
Because there is no default `turn` or `rotation` unit defined, conversion from rpm or rps to rad/s gives incorrect results. As an example `1rps |> rad/s` should result in `2*pi rad/s` but the conversion pipeline results in `1//1 rad s^-1` which is incorrect. Changing the definition of RPM to `(2*pi)rad/minute` fixes the problem but requires rad be defined and may cause other problems I'm not familiar with.

**Comment by ajkeller34** [comment]
Thanks for the report. Please see the referenced PR.

**Comment by jordancluts** [comment]
Thank you! Glad to see this get fixed!
