### ISSUE TITLE
Determining number type without adding a Unitful dependency

### ISSUE THREAD

**Issue by richardreeve** [PainterQubits/Unitful.jl#262]
I'm fixing a lot of bugs in handling of different types in JuliaStats/Distributions.jl#951, and I would very much like to be able to add the ability to generate Unitful random numbers. However, I don't see how to tell that I've got a floating point number without adding a Unitful dependency:

```julia
w = 1.0f0
numtype(w) <: AbstractFloat # Requires Unitful dependency
x = 1.0m
numtype(x) <: AbstractFloat
```

That obviously works, but `numtype` is from `Unitful`. I want to be able to do this without depending on Unitful. I'm just wondering whether it would be possible to reuse `eltype`, so:

```julia
w = 1.0f0
eltype(w) === Float32 # Succeeds, no dependency
x = 1.0m
eltype(x) === Float64 # Fails - return Quantity...
```

Is that a possibility? Or is there another solution?

**Comment by timholy** [comment]
```julia
julia> x = 1.0m
1.0 m

julia> one(x)
1.0

julia> y = 1m
1 m

julia> one(y)
1
```
should show a potential way forward.

**Comment by richardreeve** [comment]
Ah, I see - I assumed `one(2.0m) == 1.0m`, but I see that's `oneunit(2.0m)`...

**Comment by richardreeve** [comment]
Gah. I've just realised that I can do this and it works for Unitful numbers and normal real numbers, but it doesn't work for examples like `ForwardDiff.Dual`, which is the current example of a weird number in `Distributions`, and returns itself when you call `one(d)`... any thoughts?

**Comment by richardreeve** [comment]
At the moment the best I have is `typeof(one(μ) / one(μ)) ≡ typeof(one(μ))`...

**Comment by richardreeve** [comment]
Even worse @timholy:
```julia
julia> x=1.0m
1.0 m

julia> one(x)
1.0

julia> zero(x)
0.0 m
```
I presume that's a bug!

**Comment by timholy** [comment]
No it's not.

```julia
help?> one
search: one ones oneunit isone exponent ExponentialBackOff convert convertr convertrp convexhull corner2subpixel uconvert uconvertp uconvertrp imcorner istaskdone AssertionError imcorner_subpixel

  one(x)
  one(T::type)

  Return a multiplicative identity for x: a value such that one(x)*x == x*one(x) == x.
...
help?> oneunit
search: oneunit DimensionlessQuantity HomogeneousPoint

  oneunit(x::T)
  oneunit(T::Type)

  Returns T(one(x)), where T is either the type of the argument or (if a type is passed) the argument. This differs from one for dimensionful quantities: one is dimensionless (a multiplicative identity)
  while oneunit is dimensionful (of the same type as x, or of type T).
...
help?> zero
search: zero zeros zeroarray iszero set_zero_subnormals get_zero_subnormals count_zeros RoundToZero leading_zeros trailing_zeros RoundFromZero finalizer UndefInitializer ColorizedArray

  zero(x)

  Get the additive identity element for the type of x (x can also specify the type itself).
```
The point being that the additive identity has the same units, but the multiplicative identity does not. `1m*1m = 1m^2`, not `1m`. But `0m + 0m = 0m`.

If you can't solve this with generic functions but don't want to add `Unitful` as a dependency, perhaps the answer is a common numeric traits package. `Unitful`, `Distributions`, and `ForwardDiff` could all use it as a dependency.

**Comment by richardreeve** [comment]
Okay, just me not reading the docs - sorry.

**Comment by timholy** [comment]
You're not the first to have wondered, and I appreciate your interest in solving these difficult issues!

**Comment by richardreeve** [comment]
Ah, the wonders of irrational numbers:
```julia
isuncountable(x) = x isa Number && typeof(one(x) / π) ≡ typeof(one(x))
```
