### ISSUE TITLE
`zero(Quantity{Int64, D, U} where U where D)` should error?

### ISSUE THREAD

**Issue by goretkin** [PainterQubits/Unitful.jl#264]
```julia
julia> zero(Quantity{Int64, D, U} where U where D)
0
```

This happens via a fallback to
```julia
julia> convert(Quantity{Int64, D, U} where U where D, 0)
0
```

The `convert` behavior makes sense, since it returns a representation of `0` of type `Quantity{Int64, D, U} where U where D`. But I'm not sure what it means to return the zero element of a quantity whose units are not specified.

I came to this conclusion via https://github.com/JuliaLang/julia/issues/33099 which, in my opinion, erroneously succeeds and should have instead failed under the fallback for `zero`.

**Comment by ajkeller34** [comment]
I think this should be fixed now—I also implemented behavior for types like `Quantity{Int64, 𝐋}`.
