### ISSUE TITLE
Idea: Overload `Base.in` for easier reading

### ISSUE THREAD

**Issue by marius311** [PainterQubits/Unitful.jl#270]
A random idea just to put out there. If you define `Base.in(x::Quantity, u::Units) = ustrip(u,x)` then you can write stuff like, 

```julia
julia> Temperature = 2.72u"K"
julia> Temperature in u"μK"
2.72e6
```

which to me reads really nicely, since its basically exactly what you'd speak, "whats the Temperature in micro-Kelvin?" 

I don't think its really type-piracy since Units aren't really iterable. Maybe only slight abuse of the meaning of `Base.in`. Nevertheless, maybe something like this is worth including?

**Comment by giordano** [comment]
It's not type piracy nut it's a change of semantic. When reading `T in U`  you won't be able to understand if that's a conditional or a unit conversion without knowing the runtime value of `T` and `U`.

That's a fun idea, though 😀

**Comment by marius311** [comment]
I'll probably still do it in my own code and just not write ambiguous stuff, but in any case another idea is create a custom binary operator. You need to pick an standard operator to hook onto, `/` makes some sense but maybe theres better? It means you won't get something that reads as pretty as `Temperature in u"μK"` but one could imagine:

```julia
/ᵤ(x,u) = ustrip(u,x)

Temperature /ᵤ u"μK"`
```

Anyway I don't actually feel super strongly about any of this, just brainstorming for fun.

**Comment by cstjean** [comment]
I kinda like it. It's certainly no worse than `Base.getindex(::Type, args...)`, which is used to support `Float64[1,2,3]`

**Comment by ajkeller34** [comment]
For reference, this was considered a while ago, see e.g. https://github.com/PainterQubits/Unitful.jl/issues/20. At the time it was decided to use the pipe operator `|>` for unit conversion, which doesn't read as nicely but is also two characters. So far nobody has said that this behavior is problematic in practice.

**Comment by ggggggggg** [comment]
I've been using the `|>` operator which works and reads quite nice. I think punning is a bad idea here, I believe the major advantage of `Unitful` is that it allows units to work with generic programming, and that requires sticking the the definitions of all `Base` functions.

**Comment by marius311** [comment]
I would argue that `|>` is just as much of a pun as `in` since the thing on the RHS of `|>` is supposed to be a function :) but I'm content that I can define whichever I want in my code.

**Comment by singularitti** [comment]
> I would argue that `|>` is just as much of a pun as `in` since the thing on the RHS of `|>` is supposed to be a function :) but I'm content that I can define whichever I want in my code.

I think `u"something"` could be regarded as a [function (function-like object)](http://docs.julialang.org/en/v1/manual/methods/#Function-like-objects-1). Does this make `|>` less like a pun?

**Comment by sostock** [comment]
> > I would argue that `|>` is just as much of a pun as `in` since the thing on the RHS of `|>` is supposed to be a function :) but I'm content that I can define whichever I want in my code.
> 
> I think `u"something"` could be regarded as a [functor (function-like object)](http://docs.julialang.org/en/v1/manual/methods/#Function-like-objects-1). Does this make `|>` less like a pun?

That’s how I see it, too. Just like `Float64(x)` is roughly equivalent to `convert(Float64, x)`, `u"m"(x)` is equivalent to `uconvert(u"m", x)`.
