### ISSUE TITLE
What is the simple way of writing a `DimensionlessQuantity`?

### ISSUE THREAD

**Issue by singularitti** [PainterQubits/Unitful.jl#273]
I have a type that requires its 4 fields all be `AbstractQuantity`:
```julia
struct XXXX{A,B,C,D}
    v0::A
    b0::B
    bp0::C
    e0::D
end
XXXX(v0::AbstractQuantity, b0::AbstractQuantity, bp0::AbstractQuantity) = XXXX(v0, b0, bp0, 0 * u"J")
```
But the 4 fields have different physical meanings (`Dimension`, in Unitful.jl words), so they cannot be the same type (i.e., `A`, ..., `D` are not the same). But `bp0` is a `DimensionlessQuantity`. So I want to write
```julia
julia> XXXX(1u"m^3", 2u"J/m^3", 3)
ERROR: MethodError: no method matching XXXX(::Quantity{Int64,𝐋^3,Unitful.FreeUnits{(m^3,),𝐋^3,nothing}}, ::Quantity{Int64,𝐌*𝐋^-1*𝐓^-2,Unitful.FreeUnits{(J, m^-3),𝐌*𝐋^-1*𝐓^-2,nothing}}, ::Int64)
```
But this results in an error as shown above, since `3` is of type `Int64`. I can avoid this by writing
```julia
julia> XXXX(1u"m^3", 2u"J/m^3", 3u"1000mm/m")
XXXX{Quantity{Int64,𝐋^3,Unitful.FreeUnits{(m^3,),𝐋^3,nothing}},Quantity{Int64,𝐌*𝐋^-1*𝐓^-2,Unitful.FreeUnits{(J, m^-3),𝐌*𝐋^-1*𝐓^-2,nothing}},Quantity{Int64,NoDims,Unitful.FreeUnits{(mm, m^-1),NoDims,nothing}},Quantity{Int64,𝐋^2*𝐌*𝐓^-2,Unitful.FreeUnits{(J,),𝐋^2*𝐌*𝐓^-2,nothing}}}(1 m^3, 2 J m^-3, 3000 mm m^-1, 0 J)
```
But it does not make sense since `bp0` has no relation to "meter". I have tried writting
```julia
julia> XXXX(1u"m^3", 2u"J/m^3", 3u"1")
ERROR: MethodError: no method matching XXXX(::Quantity{Int64,𝐋^3,Unitful.FreeUnits{(m^3,),𝐋^3,nothing}}, ::Quantity{Int64,𝐌*𝐋^-1*𝐓^-2,Unitful.FreeUnits{(J, m^-3),𝐌*𝐋^-1*𝐓^-2,nothing}}, ::Int64)
```
But it does not work also. I think the type of `bp0` should be
```julia
Quantity{<:Real,NoDims,Unitful.FreeUnits{(),NoDims,nothing}}
```
Is there a way to quickly write a `Unitful` string literal of that type?

**Comment by ajkeller34** [comment]
If there are no units and it is dimensionless, why use a `Quantity` at all?

I think it is going to be awkward if you want to restrict the method argument type to any possible dimensionless number, which could encompass numeric types in `Base`, dimensionless `Unitful` types, and numeric types defined in other packages. I would suggest you just define `XXXX(v0::AbstractQuantity, b0::AbstractQuantity, bp0::Number)` and check the dimension of `bp0` in the function definition.

By the way, you are likely to get faster responses if you post your questions on the Julia Slack in the #helpdesk channel.

**Comment by singularitti** [comment]
> By the way, you are likely to get faster responses if you post your questions on the Julia Slack in the #helpdesk channel.

Thank you for your information!
