### ISSUE TITLE
Overload Base.log(::Quantity)?

### ISSUE THREAD

**Issue by PharmCat** [PainterQubits/Unitful.jl#279]
is it possible to include Base.log(::Quantity) to the package. 

i have a function:
```
function f(a::Number)
   b = log(a)
  # ...
end
```
and it is not working with units... or may me exist method to make if work with Int, Floats and Units

**Comment by ajkeller34** [comment]
What do you think this method should do? Can you provide some examples of desired behavior?

**Comment by PharmCat** [comment]
So why I tlaking about it: in my project i need to calculate log-concentrations and when i try to do this i have an error. 

I can make something like this in my project:

```
function Base.log(a::Quantity{T,D,U}) where T <: Real where D where U 
    return log(a.val)
end
```
but in this case i should include package in dependencies.

I understand that we loss units in this case, but log() is only a number.

also if i want to make type independent code i need to do some things for comporations:

```
a = 1000u"g"
#to check > 0
if a > a*0
   #do some
end
```

**Comment by ajkeller34** [comment]
I don't think it is meaningful to just strip all unit info and take the log. The usual way to take a log of a quantity is to use a reference value. So for example if you want to know how many orders of magnitude above or below 1 Molar, you could divide your concentration by 1 Molar and take `log10`, perhaps. Would that work for you? There's also logarithmic unit support but that's a bit more involved. I'm going to close this issue but if you have follow up questions I'll try to answer (there'a also the Julia Slack and the discussion forum on Discourse for usage/help questions).

**Comment by PharmCat** [comment]
> 
> 
>  Would that work for you? 
Unfortunately not. After log-transformation I'm finding slope for part of the data. And function should work type independent.
