### ISSUE TITLE
Printing of Complex Unitful quantities is confusing. 

### ISSUE THREAD

**Issue by MasonProtter** [PainterQubits/Unitful.jl#285]
When one does
```julia
julia> using Unitful

julia> (1 + im)u"m"
1 + 1im m
```
it looks like this is saying `1 + (1im m)` instead of `(1 + 1im) m`. It'd be good to have a special case for `show` so that this is printed more clearly.

**Comment by c42f** [comment]
Seems quite related to https://github.com/PainterQubits/Unitful.jl/issues/199.

Perhaps we should flip the default `show` to just add brackets in the style of https://github.com/PainterQubits/Unitful.jl/pull/256, with special cases to opt out?
