### ISSUE TITLE
Move to version 1.0

### ISSUE THREAD

**Issue by giordano** [PainterQubits/Unitful.jl#289]
Today I added the `Project.toml` to an old package I maintain.  It has this nice compat line:
```
Unitful = "0.9, 0.10, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18"
```
Any new feature is a minor version bump, which is a breaking change for SemVer.  This package has a quite stable API, and SemVer is only about API, not quality of the code, so maybe it's time to move on to version 1.0?

**Comment by alhirzel** [comment]
I propose #214 is fixed for 1.0 because I consider it an important feature.

**Comment by ajkeller34** [comment]
I agree, it is time for 1.0: https://github.com/PainterQubits/Unitful.jl/pull/301

I don't see anything seriously holding up this release at the moment. We can always release a 1.0.1 or 1.1 as needed in short order. I'll leave this open for just a short while to see if any comments pop up.

**Comment by ajkeller34** [comment]
at long last, https://github.com/JuliaRegistries/General/pull/8483
