### ISSUE TITLE
some of type information string is not displayed right

### ISSUE THREAD

**Issue by yongheekim-dev** [PainterQubits/Unitful.jl#304]
![image](https://user-images.githubusercontent.com/42163454/74011052-38008100-49ca-11ea-994e-3d3e57111e67.png)

My font on Julia console is MS Gothic. 
and this is copied string from console
```
Quantity{Int64,�,Unitful.FreeUnits{(m,),�,nothing}}
```

**Comment by ajkeller34** [comment]
You might have better luck if you launch Julia from within a mintty terminal / Git Bash. For MS Gothic, the symbol appears in Git Bash but does not appear in the default Julia terminal. That said, it doesn't look very legible for this font, you're supposed to see a bold-face L:

<img width="308" alt="image" src="https://user-images.githubusercontent.com/7145721/74094084-1538a000-4a90-11ea-88bb-69ce0eb0b01a.png">

So, I suggest changing both your default terminal and your font. On Windows the default terminal may be changed out soon: https://github.com/JuliaLang/julia/issues/7267
