### ISSUE TITLE
Tag new release (v1.0.1?)

### ISSUE THREAD

**Issue by briochemc** [PainterQubits/Unitful.jl#316]
There have been a bunch of useful commits and merges since 1.0.0 (e.g., Unitful exponents making UnitfulRecipes so much nicer). Could you guys make a new release with these? (I think v1.0.1 should do but maybe I'm unaware of some changes that would warrant a bigger bump)

**Comment by briochemc** [comment]
Is there anything holding this up?

**Comment by giordano** [comment]
[v1.1.0](https://github.com/PainterQubits/Unitful.jl/releases/tag/v1.1.0) released
