### ISSUE TITLE
Consider deleting custom show methods for types

### ISSUE THREAD

**Issue by andreasnoack** [PainterQubits/Unitful.jl#321]
I.e. https://github.com/PainterQubits/Unitful.jl/blob/7fb2dfb68c63c0a77b8c859c294d8b7f03f337d6/src/display.jl#L80-L85. There are two reasons for this.

The first is that, according to the compiler team, the base methods are not supposed to be overloaded. It's not documented and not obvious but it's been assumed that `show(::IO, ::Type)` isn't overloaded by user code so doing that can lead to very odd issues. E.g. the definitions in this package might have caused Documenter to hang for one of my packages because Documenter prints the signature of methods with missing docs.

The second reason is that it can be super confusing when types print differently from what they really are. I've had some issues with that when using this package because I based some function signatures on how the types were printed in the REPL only to get an error because the signature didn't match.

**Comment by cstjean** [comment]
> The first is that, according to the compiler team, the base methods are not supposed to be overloaded. It's not documented and not obvious but it's been assumed that show(::IO, ::Type) isn't overloaded by user code so doing that can lead to very odd issues

The docs really need to change then, because this section clearly overloads `Base.show(io::IO, z::Polar)`:

https://docs.julialang.org/en/v1.4/manual/types/#man-custom-pretty-printing-1

**Comment by andreasnoack** [comment]
Defining `Base.show(io::IO, z::Polar)` is fine. The problem would be to define e.g. `Base.show(io::IO, z::Type{<:Polar})`

**Comment by cstjean** [comment]
Oh, right, sorry for the noise. I need to read more carefully.

**Comment by timholy** [comment]
Old history here: https://github.com/JuliaLang/julia/issues/13306. Not sure how much of a modern problem it is, but I've been paranoid about specializing `show` for types ever since.

I wonder if we need `showtype` to do pretty-printing of types and decide on which places use the pretty and which use the raw. In general I would have thought method signatures should be printed prettily, but it sounds like that would have caused the same bug you got with Documenter.

**Comment by ajkeller34** [comment]
It would be very useful to have something like `showtype`. Unitful uses values as type parameters (dimensions, for example). I don't think it is clear how to make such types show in a way where you can paste them into a REPL and have them evaluate correctly, in general. The values don't know they are being shown inside of a type signature.
