### ISSUE TITLE
Fix uconvert For Inverse Units

### ISSUE THREAD

**Issue by acdupont** [PainterQubits/Unitful.jl#338]
`uconvert` does not calculate the correct value for inverse units.

This works as expected:
```
julia> uconvert(u"m^3", 1000000.0u"cm^3")
1.0 m^3
```

When using inverse units, I expected the value `1.0 m^-3` but got this instead
```
julia> uconvert(u"m^-3", 1000000.0u"cm^-3")
1.0e12 m^-3
```

**Comment by giordano** [comment]
@briochemc this works on v1.2.0 but not v1.2.1.  Looks like #335 wasn't enough

**Comment by acdupont** [comment]
hmm, I think my logic is wrong. if there are 1000000 "things" per cm^3, then there will be a magnitude more than that in a m^3, so it looks like Unitful's answer here actually is correct.

**Comment by giordano** [comment]
Also, I was testing the wrong function in the REPL :expressionless:  The result is consistent across all versions v1, v1.1, v1.2.0, v1.2.1.  @briochemc Sorry for the noise!

**Comment by giordano** [comment]
> hmm, I think my logic is wrong. if there are 1000000 "things" per cm^3, then there will be a magnitude more than that in a m^3, so it looks like Unitful's answer here actually is correct.

Yes, this is a volumetric density, so if you go to a larger volume you expect "more stuff", and the factor 10^6 when going from a volume of 1cm^3 to 1m^3 looks indeed correct.  Ok, I think we can close this ticket.
