### ISSUE TITLE
In Pluto notebook: @u_str not defined

### ISSUE THREAD

**Issue by rc83** [PainterQubits/Unitful.jl#377]
I am using this module inside Pluto notebook (by @fonsp at https://github.com/fonsp/Pluto.jl/). If I try to import and use the module in the same notebook cell I get an error.

The cell:
```
begin
	using Unitful
	1u"m"
end
```

The output:
```
LoadError: UndefVarError: @u_str not defined

in expression starting at /tmp/Important report.jl#==#0284e210-ee1a-11ea-27cd-c1f257bf7fb9:3

    top-level scope@:0
    top-level scope@Parse.jl:111
    (::Distributed.var"#101#102"{Distributed.CallMsg{:call}})()@process_messages.jl:290
    run_work_thunk(::Distributed.var"#101#102"{Distributed.CallMsg{:call}}, ::Bool)@process_messages.jl:79
    run_work_thunk(::Distributed.RemoteValue, ::Function)@process_messages.jl:88
    (::Distributed.var"#94#96"{Distributed.RemoteValue,Distributed.var"#101#102"{Distributed.CallMsg{:call}}})()@task.jl:358
```

However, if I split import (`using Unitful`) and actual usage (`1u"m"`) into different notebook cells, it runs as expected. I wonder if this is a bug (_Unitful_'s or _Plutos_'s?) or a feature. Thank you for the clarification and perhaps a short warning note in the documentation.

**Comment by fonsp** [comment]
Macros are only defined after the expression, so
```
begin
    using Example
    @macrofromexample
end
```

will not work - Julia macros expand _before_ the expression is evaluated

**Comment by fonsp** [comment]
The solution is to split you code into cells 🙂

Pluto 0.11.11 can automatically split multiple-expression code into N cells

**Comment by giordano** [comment]
I think this issue has nothing to do with this package, closing it
