### ISSUE TITLE
pH unit

### ISSUE THREAD

**Issue by rmsrosa** [PainterQubits/Unitful.jl#386]
Hi,

I didn't see "pH" in Unitful.jl so I defined "pH" as a logarithmic unit, but I got a warning of an already defined "pH" quantity in Unitful.jl and which is dimensional:

```julia
julia> typeof(Unitful.pH)
Unitful.FreeUnits{(pH,),𝐋² 𝐌 𝐈⁻² 𝐓⁻²,nothing}
```

What exactly is this `Unitful.pH`? 

Is it related to how pH is measured in an electronic pH meter? 

In any case, shouldn't this get a different notation and leave "pH" to be the logarithmic scale "power of Hydrogen"?

**Comment by sostock** [comment]
`Unitful.pH` is the unit picohenry. Henry (`H`) is the SI unit of electrical inductance.

**Comment by rmsrosa** [comment]
Ah, I see. Yes, and that explains why it didn't show up in `grep`.

So I will have to decide whether to override the notation or use a different one, maybe `pwrH` or `pH+`. I will think about.

Thanks!
