### ISSUE TITLE
Add cgs-units oersted and gauss

### ISSUE THREAD

**Issue by KronosTheLate** [PainterQubits/Unitful.jl#395]
In working in a project involving magnetization I am having to deal with some old litterature that uses the CGS units "gauss" and "oersted" (as opposed to the SI-equivalent Tesla and A/m). Is there any reason why they should not be added under `# CGS units` in src/pkgdefaults.jl? And if, based on this post, I was to implement them, would it be sufficient to add equivalent definitions as can be seen under `#CGS units`? E.g 
```
@unit Gs "Gs"      Gauss      1e-4kg/(A*s^2)               true
@unit oe "oe"      oersted    1/4π*1000A/m                 true
```

**Comment by sostock** [comment]
I don’t see any reason against adding these units, although we would need to use a different symbol for `Gauss`. Both `G` and `Gs` are already taken (`Gs` is the unit gigasecond, `G` is the gravitational constant).

It would be sufficient to add these definitions, although the definition of `Gauss` could be improved: `1e-4` is a floating-point number, it would be better to use `(1//10_000)kg/(A*s^2)` or simply `(1//10_000)T`.

**Comment by KronosTheLate** [comment]
> I don’t see any reason against adding these units, although we would need to use a different symbol for `Gauss`. Both `G` and `Gs` are already taken (`Gs` is the unit gigasecond, `G` is the gravitational constant).

Annoying. I settled on "Gauss", as I found no nice shorthand and it is clear. I also saw that "oe" should be capitalized (it was in the wikipedia article), and threw in maxwell for completeness.

> It would be sufficient to add these definitions, although the definition of `Gauss` could be improved: `1e-4` is a floating-point number, it would be better to use `(1//10_000)kg/(A*s^2)` or simply `(1//10_000)T`.

Nice! Thanks

Here is the PR:
https://github.com/PainterQubits/Unitful.jl/pull/397
