### ISSUE TITLE
Question: promotion to acceleration unit?

### ISSUE THREAD

**Issue by MartinOtter** [PainterQubits/Unitful.jl#409]
A short question:

```
using Unitful
m = 1.1u"kg"
f = 2.2u"N"
a = f/m  # a = 2.0 N kg^-1
```
I would have expected that the acceleration `a` has unit `m s^-2`. I have read about [unit promotion](https://painterqubits.github.io/Unitful.jl/stable/conversion/), but could not figure out, how to force transformation of a result to SI base units.

**Comment by sostock** [comment]
You can call `upreferred(a)` to get the result in base SI units.

**Comment by MartinOtter** [comment]
Thanks. Yes, this works:
```
using Unitful
m = 1.1u"kg"
f = 2.2u"N"
a = upreferred(f/m)  # 2.0 m s^-2
```
