### ISSUE TITLE
Add doc strings to units?

### ISSUE THREAD

**Issue by kbarros** [PainterQubits/Unitful.jl#436]
No documentation turns up here:
```
help?> Unitful.F
  No documentation found.

  Unitful.F is of type Unitful.FreeUnits{(F,), 𝐈² 𝐓⁴ 𝐋⁻² 𝐌⁻¹, nothing}.

  Summary
  ≡≡≡≡≡≡≡≡≡

  struct Unitful.FreeUnits{(F,), 𝐈² 𝐓⁴ 𝐋⁻² 𝐌⁻¹, nothing} <: Unitful.Units{(F,), 𝐈² 𝐓⁴ 𝐋⁻² 𝐌⁻¹, nothing}
  [...]
```

Would it be help to have an autogenerated doc string that says, e.g.,
```
Untiful.F defines the Farad as 1s^4*A^2/(kg*m^2) with dimensions 𝐈² 𝐓⁴ 𝐋⁻² 𝐌⁻¹
```
It seems this should be possible since pkgdefaults.jl defines
```
@unit F               "F"    Farad           1s^4*A^2/(kg*m^2)  true
```

**Comment by lukebemish** [comment]
An interesting question arises, were someone to try and implement this; should this express the definition the way it is described in the macro ("1 ft is 12 inches") or the conversion relative to preferred units ("1 ft is 381//1250 m")? I can see pros and cons to each. My personal vote would be for the second, as it looks a bit easier to implement, and is a bit more convenient to have all definitions relative to a single unit.
