### ISSUE TITLE
Bug? 10u"MeV" == 10000u"keV" returns "false"

### ISSUE THREAD

**Issue by tetsuosnd** [PainterQubits/Unitful.jl#449]
I report the folloiwng issue. I might find a bug.
I have found that 
julia> 10u"MeV" == 10000u"keV"
false
It is obviously incorrect.
On the other hand, I have gotten the correct answer in similar cases;
julia> 1u"MeV" == 1000u"keV"
true
julia> 100u"MeV" == 100000u"keV"
true
julia> 10u"Ms" == 10000u"ks"
true

**Comment by giordano** [comment]
Floating point numbers :shrug: 
```julia
julia> promote(10u"MeV",10000u"keV")
(1.6021766339999997e-12 kg m^2 s^-2, 1.602176634e-12 kg m^2 s^-2)
```
Just never use `==` when floating point numbers are involved, use `isapprox` instead:
```julia
julia> 10u"MeV" ≈ 10_000u"keV"
true
```

**Comment by tetsuosnd** [comment]
Thank you so much.
I missed that the "eV" is treated as a floating-point number.

**Comment by giordano** [comment]
It isn't that "eV" itself is treated as a floating point number, but conversions between different units may involve floating point numbers.  You can see in `promote(10u"MeV",10000u"keV")` that the two quantities are converted to kg m^2 s^-2, before comparing them, and this conversion does involve floating point numbers.
