### ISSUE TITLE
We have `sincos`, but no `sincosd`?

### ISSUE THREAD

**Issue by singularitti** [PainterQubits/Unitful.jl#450]
It was added in Julia 1.3. But can we have it for, like, `5u"°"`?

**Comment by sostock** [comment]
This could be solved by removing the type restriction of the `sincosd(::Real)` method in `Base`. After all, there is a `sincos(::Any)` method in `Base` which is called for quantities (Unitful does not define its own `sincos` method).

**Comment by singularitti** [comment]
Can we define a temporary workaround `sincosd` just for `Unitful` degrees? It is not type piracy and `Base` only changes when Julia has a new version. It cannot be used in older Julia versions.

**Comment by sostock** [comment]
I think it’s okay to define a `sincosd` method for degrees here.

Unrelated to that, I did not know that `sin(5°)` and `sind(5°)` return the same number. The behavior of `sind` seems wrong to me, since `5° == 5*pi/180`, so `sind(5°)` should be equal to `sind(5*pi/180)` as well. In general, I think that `sind(x)` should be equal to `sin(x*pi/180)`. I would suggest to remove the `sind` method for Unitful 2.0 and to only leave the method which simplifies `sin(x*u"°")` to `sind(x)` (and the same for `cos`, `tan`, etc.).

**Comment by singularitti** [comment]
I have added a [`sincosd` in Julia base module in this PR](https://github.com/JuliaLang/julia/pull/41021), but it can only be introduced in the next version.

> Unrelated to that, I did not know that `sin(5°)` and `sind(5°)` return the same number. The behavior of `sind` seems wrong to me, since `5° == 5*pi/180`, so `sind(5°)` should be equal to `sind(5*pi/180)` as well. In general, I think that `sind(x)` should be equal to `sin(x*pi/180)`. I would suggest to remove the `sind` method for Unitful 2.0 and to only leave the method which simplifies `sin(x*u"°")` to `sind(x)` (and the same for `cos`, `tan`, etc.).

`sind(5u"°") == sind(5)` and `cosd(5u"°") == cosd(5)` seem natural to me. Since `sind` "compute sine of x, where x is in degrees." So if `5u"°"` is already in degree, it should do nothing else, just return `sind(5)`. If `sind` for `u"°"` is removed, people cannot use that for both a number and a `Quantity`, that seems breaking. I hope we could keep its current behavior.

**Comment by sostock** [comment]
It doesn’t seem natural to me, since `5u"°" == 0.08726646259971647`, not `5u"°" == 5`. I don’t think special-casing `u"°"` is consistent, since it makes the result noninvariant under unit conversion, which is something that this package tries to avoid:
```julia
julia> x = 5u"°"
5°

julia> xs = (x, uconvert(NoUnits,x), uconvert(u"mm/m", x))
(5°, 0.08726646259971647, 87.26646259971648 mm m^-1)

julia> sin.(xs)
(0.08715574274765818, 0.08715574274765817, 0.08715574274765817)

julia> sind.(xs)
(0.08715574274765818, 0.0015230865100588134, 0.0015230865100588132)
```

**Comment by singularitti** [comment]
I don't think anyone will ever convert `5u"°"` to `u"mm/m"`, that's totally unphysical. Convert to `NoUnits`, that could happen. `sin` and `sind` are different functions with different physical meanings, they could have different results. I still think `sind` should do what is [documented](http://docs.julialang.org/en/v1/base/math/#Base.Math.sind), rather than being too consistent. Ideally, I agree we should remove `sind` for `u"°"`, but now I just want to use it "as is". [In my code](https://github.com/MineralsCloud/Crystallography.jl/blob/bff3af79f851b2f452d8f7f381c95ecb64e20ea0/src/transform.jl#L49), I just want users to use either `Int` 5 or `5u"°"` without changing their code.

**Comment by singularitti** [comment]
To me, `5u"°" == 0.08726646259971647` is actually strange, because `5u"°"` is a `Quantity` and `0.08726646259971647` is a `Float64`. It should actually be

```julia
julia> 5u"°" == 0.08726646259971647u"rad"
true
```

By saying `5u"°" == 0.08726646259971647`, we actually are ignoring `u"rad"` is also a unit, just as `5u"°"`. `5u"°"` should not be equal to `0.08726646259971647` in the beginning, IMHO.

**Comment by sostock** [comment]
> To me, `5u"°" == 0.08726646259971647` is actually strange, because `5u"°"` is a `Quantity` and `0.08726646259971647` is a `Float64`.

Why should a `Quantity` not be able to be equal to a `Float64`? To me, `5u"mm/m" == 0.005` makes sense. It is correct and useful.

> It should actually be
> ```julia
> julia> 5u"°" == 0.08726646259971647u"rad"
> true
> ```
That is true as well. `rad` is a dimensionless unit and `1u"rad" == 1`.

> By saying `5u"°" == 0.08726646259971647`, we actually are ignoring `u"rad"` is also a unit, just as `u"°"`. `5u"°"` should not be equal to `0.08726646259971647` in the beginning, IMHO.

I think it’s highly unlikely that we will remove the ability to compare quantities and non-quantities.

**Comment by singularitti** [comment]
> Why should a Quantity not be able to be equal to a Float64?
I mean, `5u"°" == 87.26646259971648 mm m^-1` is unphysical. You can do `uconvert(NoUnits, x)` to `5u"°"`, sure.
I think `5u"°"` and `0.08726646259971647` are not really "equal", by saying equal, you are assuming there is a conversion. After the conversion, they are equivalent. All I want to say is,

```julia
julia> 5u"°" == 0.08726646259971647
true

julia> 5u"°" === 0.08726646259971647
false
```
They are equivalent after a conversion, but they are different things after all.

**Comment by sostock** [comment]
> I mean, `5u"°" == 87.26646259971648 mm m^-1` is unphysical.

Do you think `5u"mm/m" == 0.005` is unphysical as well? Or do you think that angles shouldn’t be dimensionless?

> They are equivalent after a conversion, but they are different things after all. So `sind` can have different behaviors.

`5` and `5.0` are different things as well, but I would be _very_ surprised if `sind(5)` and `sind(5.0)` didn’t return the same number.

**Comment by singularitti** [comment]
> Do you think 5u"mm/m" == 0.005 is unphysical as well?

No. This is fine.

I checked the definition of radians again, I guess `5u"°"` could be in unit `5u"mm/m"` because we can regard `mm` corresponds to arc length and `m` corresponds to radius.

> Or do you think that angles shouldn’t be dimensionless?

Angles should be dimensionless, sure. I guess it's just somewhere in my mind thinking `5u"°"` is different than `0.08726646259971647`. Maybe it's me.

> 5 and 5.0 are different things as well, but I would be very surprised if sind(5) and sind(5.0) didn’t return the same number.

To me, the relationship between `5` & `5.0`, and `5` & `5u"°"` are different. It does not seem to be an appropriate comparison. `5` and `5.0` are mathematically equivalent, therefore no mathematical conversion is here. We need `5.0` just because of the limit of macinery.
