### ISSUE TITLE
Cannot convert amu to kg

### ISSUE THREAD

**Issue by lamorton** [PainterQubits/Unitful.jl#471]
```julia
julia> uconvert(u"u",u"kg")
ERROR: MethodError: no method matching uconvert(::Unitful.FreeUnits{(u,), 𝐌, nothing}, ::Unitful.FreeUnits{(kg,), 𝐌, nothing})
Closest candidates are:
  uconvert(::Unitful.Units, ::Missing) at /Users/lmorton/.julia/packages/Unitful/yI5QN/src/conversion.jl:90
  uconvert(::Unitful.Units, ::Level) at /Users/lmorton/.julia/packages/Unitful/yI5QN/src/logarithm.jl:122
  uconvert(::Unitful.Units, ::Gain) at /Users/lmorton/.julia/packages/Unitful/yI5QN/src/logarithm.jl:126
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[3]:1
```

**Comment by giordano** [comment]
Quoting from [`uconvert`](https://painterqubits.github.io/Unitful.jl/stable/conversion/#Unitful.uconvert) docstring:

>     uconvert(a::Units, x::Quantity{T,D,U}) where {T,D,U}
> Convert a [`Unitful.Quantity`](https://painterqubits.github.io/Unitful.jl/stable/types/#Unitful.Quantity) to different units. The conversion will
> fail if the target units `a` have a different dimension than the dimension of
> the quantity `x`. You can use this method to switch between equivalent
> representations of the same unit, like `N m` and `J`.
> Example:
> ```julia
> julia> uconvert(u"hr",3602u"s")
> 1801//1800 hr
> julia> uconvert(u"J",1.0u"N*m")
> 1.0 J
> ```

You don't convert a unit to another unit, but a quantity to another unit.  Also, you got the arguments in the wrong order:
```julia
julia> uconvert(u"kg", 1 * u"u")
1.6605390666e-27 kg
```
