### ISSUE TITLE
Macro to import units as variable names

### ISSUE THREAD

**Issue by hellmrf** [PainterQubits/Unitful.jl#475]
I think it would be great to have a macro that automatically imports some unities, for example:
```julia
julia> using Unitful
julia> @importunits g mol
julia> MM = 5g/mol # more legible than 5u"g/mol"
5 g mol^-1
```
For all effects, `@importunits g` is expanded to `const g = uparse("g")`.

I've already written such macro for myself, but maybe it would be interesting to include it in the package:
```julia
macro importunits(units...)
    ex = Expr(:block)
    ex.args = [:(const $unit = uparse( $(string(unit)) )) for unit in units]
    return esc(ex)
end
```

**Comment by sostock** [comment]
You can already do
```julia
using Unitful: g, mol
```
Therefore, I think an `@importunits` macro doesn’t add much value (it only saves a few keystrokes).

**Comment by hellmrf** [comment]
Oh, great. I was not aware. Thank you!
