### ISSUE TITLE
NaturallyUnitful

### ISSUE THREAD

**Issue by Mo8it** [PainterQubits/Unitful.jl#480]
Please merge [NaturallyUnitful](https://github.com/MasonProtter/NaturallyUnitful.jl) or at least mention it :)

**Comment by sostock** [comment]
I don’t see a PR related to NaturallyUnitful, so I’m confused as to what should be merged. Of course we can mention it in the README. Someone just needs to make a PR that adds it to the list.

**Comment by Mo8it** [comment]
The pull request is ready. I am waiting for the agreement of the original author of NaturallyUnitful.jl @MasonProtter :)

https://github.com/Mo8it/Unitful.jl/tree/feature/natural_units

**Comment by Mo8it** [comment]
Ready: https://github.com/PainterQubits/Unitful.jl/pull/481

**Comment by sostock** [comment]
Added to README in #483.
