### ISSUE TITLE
one and zero exhibit different behaviors.

### ISSUE THREAD

**Issue by HaoxuanGuo** [PainterQubits/Unitful.jl#508]
```julia
one(3u"mm")  # 1
zero(3u"mm")  # 0 mm
```

Is it a bug?

**Comment by sostock** [comment]
No, that’s the expected behavior.

* `zero` is the additive identity, i.e., `x + zero(x) == x`.
* `one` is the multiplicative identity, i.e., `x * one(x) == x`.

There is also `oneunit(3u"mm") == 1u"mm"`, maybe that’s what you want.
