### ISSUE TITLE
feature request / suggestion

### ISSUE THREAD

**Issue by ngam** [PainterQubits/Unitful.jl#523]
```julia
julia> using Unitful

julia> a = 500*u"K"
500 K

julia> a |> unit
K

julia> b = [500,550]*u"K"
2-element Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}}:
 500 K
 550 K

julia> b |> unit
ERROR: MethodError: no method matching unit(::Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}})
Closest candidates are:
  unit(::Union{Dates.Day, Dates.Hour, Dates.Microsecond, Dates.Millisecond, Dates.Minute, Dates.Nanosecond, Dates.Second, Dates.Week}) at ~/.julia/packages/Unitful/SUQzL/src/dates.jl:31
  unit(::Base.TwicePrecision{Q}) where Q<:Quantity at ~/.julia/packages/Unitful/SUQzL/src/units.jl:281
  unit(::Unitful.MixedUnits{L, U}) where {L, U} at ~/.julia/packages/Unitful/SUQzL/src/logarithm.jl:98
  ...
Stacktrace:
 [1] |>(x::Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}}, f::typeof(unit))
   @ Base ./operators.jl:911
 [2] top-level scope
   @ REPL[5]:1

julia> b .|> unit
2-element Vector{Unitful.FreeUnits{(K,), 𝚯, nothing}}:
 K
 K

julia> 

```

My understanding is that the current behavior of the unit utility (and associated utilities) is to work only on non-vectored quantities and instead rely on Julia's mechanics to parse vectored quantities (hence, the use of `.|>` instead of `|>` above). I think this somewhat related to the source code being written only for `::Number` and the like types. This is actually a pretty good idea to reduce the work here! And it allows for great flexibility (e.g. vectors with different units, `c = [300*u"K", 300]*u"K"` though with a big performance penalty as described in the docs).

However, realistically, people will often use vectored quantities with uniform units (i.e. either unitless or with one unit only). So, this flexibility can be a little more difficult to work with especially in situations with control flow. After all, when I think of a vector with units, I don't think of it as a a vector and a vector of units, but rather a numerical vector that happens to have a single unit. So in defining `b` above, I write `b = [500,550]*u"K"` expecting a numerical vector (`[500,550]`) with a single unit (`u"K"`). Instead, Julia/Unitful broadcast the unit on every element, which is also okay because by definition that is what a vector with a single unit means. But the single unit becomes a vector of units and can no longer be retrieved directly as a single unit. For example,

```julia
julia> b .|> unit
2-element Vector{Unitful.FreeUnits{(K,), 𝚯, nothing}}:
 K
 K

julia> b .|> unit == u"K"
false

julia> b .|> unit == [u"K",u"K"]
true

julia> unit.(upreferred.(b)) == unit.(ustrip.(b) .* u"K")
true

```

Proposal:

It would be good to have a utility (e.g. unit or unitv or whatever) that can parse out the unit of a vectored quantity such that it returns that unit only and not a vector of units. I think it would be disruptive to change how `unit` works just for this, but how about introducing vectorized versions of these utilities here?

For the end user, this will be beneficial and more straightforward way to code. However, the alternative is actually not all that bad --- so a user can indeed just write a simple user utility to do this for them. For example, I found that `unit.(upreferred.(b)) == unit.(ustrip.(b) .* u"K")` does the trick reasonably well to avoid the bitVector boolean stuff in my workflow. 

I am opening this issue and proposing this here because 1) maybe this is  a helpful addition, but 2) maybe I am not taking full advantage of other utilities that already do something similar. Also, 3) as a beginner, I find it so interesting that you only define things for single quantities and rely on the underlying Julia mechanics to transform all of that to vectors/arrays, so I would very much like to hear more about that throught process! 

Please let me know what you think. Thanks!

**Comment by giordano** [comment]
I think I'm missing what you expect to get when you have a vector inhomogenous quantities.

**Comment by ngam** [comment]
> I think I'm missing what you expect to get when you have a vector inhomogenous quantities.

I would expect it to return an error in this case. That is, I wouldn't want it to factor out a common unit because I think that would defeat the purpose of all of this.

**Comment by ngam** [comment]
(Note, this is not for the current implementation of `unit` --- I would leave that untouched. I am proposing a new utility, call it `umultidim` or something like that)

**Comment by giordano** [comment]
> I would expect it to return an error in this case. 

I'm pretty sure that's contrary to the expectation of many users (including mine).

**Comment by ngam** [comment]
Yes, sorry , I should have qualified that I would expect _the new utility_ to return an error: (Note, this is not for the current implementation of unit --- I would leave that untouched. I am proposing a new utility, call it umultidim or something like that)

**Comment by sostock** [comment]
Note that you can also call `unit` on the *type* of a quantity, so the following works:
```julia
julia> b = [500,550]*u"K"
2-element Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}}:
 500 K
 550 K

julia> b |> eltype
Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}

julia> b |> eltype |> unit
K
```

Your proposed `umultidim` could just be implemented like that:
```julia
umultidim(x) = unit(x)
umultidim(x::AbstractArray) = unit(eltype(x))
```

Since it’s so easy to implement, I don’t think it’s worth adding a function for it. A user can just implement this function in their own package if they want it.

**Comment by sostock** [comment]
I just noticed that `unit` on types returns something unexpected for heterogeneous types:
```julia
julia> c = [1u"m", 2u"s"]
2-element Vector{Quantity{Int64}}:
 1 m
 2 s

julia> c |> eltype |> unit # returns `NoUnits`, which is printed empty


julia> julia> unit(Quantity{Int})


```

IMO, this is very misleading. I would have expected `unit` to throw an error if the argument does not have a well-defined unit, not just return `NoUnits`.

Of course, this can be seen as a pun on the `NoUnits` value (i.e., that in this case `NoUnits` doesn’t mean that the unit is the dimensionless unit equal to `1`, but it instead it literally means that the argument has *no units*). But I think using `NoUnits` for both of these meanings is not helpful. I think of `NoUnits` as an actual unit, not a placeholder for the case that a value does not have well-defined units.

**Comment by ngam** [comment]
> Note that you can also call `unit` on the _type_ of a quantity, so the following works:
> 
> ```julia
> julia> b = [500,550]*u"K"
> 2-element Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}}:
>  500 K
>  550 K
> 
> julia> b |> eltype
> Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}
> 
> julia> b |> eltype |> unit
> K
> ```
> 
> Your proposed `umultidim` could just be implemented like that:
> 
> ```julia
> umultidim(x) = unit(x)
> umultidim(x::AbstractArray) = unit(eltype(x))
> ```
> 
> Since it’s so easy to implement, I don’t think it’s worth adding a function for it. A user can just implement this function in their own package if they want it.

Thank you for this! I noticed the same about type actually, but I just didn't think of taking the unit of it. This is really helpful, and yes I agree with you this is not worth adding. Maybe at most a bit of documentation.

**Comment by ngam** [comment]
For more context, I have been writing (as a beginner) a collection of "input handling" utilities for a small package/project I am working on; these usually do something like this to return attach the base unit to the input (if it is in the acceptable units or non-dimensioned or throw an error (if it has the wrong unit):

```julia
"""
    ℞T(T)
Ensure T is in K.
"""
function ℞T(T)
    if unit.(upreferred.(T)) == unit.(ustrip.(T) .* u"K")
        return T .|> upreferred
    elseif unit.(upreferred.(T)) == unit.(ustrip.(T) .* Unitful.NoUnits)
        return T .* u"K"
    else
        throw(ArgumentError("Input: in K (or equivalent) or unitless"))
    end
end
```

You see, I am intentionally throwing an error for the case with heterogenous units, because in this particular case, I am simply not going to accept even something like `T = [301, 302*u"K"]` which could in theory be returned as `T = [301, 302] * u"K"`...

(Just a note: I was curious if something like `Unitful.NoUnits` is exported as cleanly as something like `u"K"`...)

**Comment by ngam** [comment]
This is ultimately the confusing part for me and hence opening this issue.

```
julia> using Unitful

julia> a = 1 * u"K"
1 K

julia> a = [1, 2] * u"K"
2-element Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}}:
 1 K
 2 K

julia> a = [1, 2]
2-element Vector{Int64}:
 1
 2

julia> a = [1*u"K", 1*u"K"]
2-element Vector{Quantity{Int64, 𝚯, Unitful.FreeUnits{(K,), 𝚯, nothing}}}:
 1 K
 1 K

julia> a = [1*u"K", 1]*u"K"
2-element Vector{Quantity{Int64}}:
 1 K²
  1 K

julia> 

```

Obviously, Unitful.jl does take the unit inside, but the way it interprets it once inside differs based on whether or not all elements have the same unit. This is what I meant --- is that really expected? It seems inconsistent, no?

So I see this a bug in the way these things trickle down (the unit and magnitude) inside the vector as opposed to it being an issue with the unit-isolating function/utility (unit). 

But I agree: Either way, the behavior is inconsistent.

**Comment by ngam** [comment]
Maybe I would expect something like:

```
julia> a = [1*u"K", 1]*u"K"
2-element Vector{Quantity{Int64, warning: mixed units}}:
 1 K²
  1 K
```

**Comment by ngam** [comment]
> What behavior in particular do you consider a bug? The only bug I see in this thread is in the `unit` function (#524).

All I am saying is that, in my limited view, the bug is not in the `unit` function but rather in the way `Quantity{T}` is assigned (as opposed to `Quantity{T,D,U}` or something equivalent). That's all. But maybe your point is that it is actually be design, then it is all good!

I am going to close this issue now since you deem the issue is best addressed in #524

**Comment by ngam** [comment]
> Is it just that you would like `Quantity{Int64}` to be printed as `Quantity{Int64, warning: mixed units}`? In my opinion, that’s really just obfuscating what the actual type is and would be more confusing for anybody who wants to know what type of elements the array can contain

Not really important --- but I thought it would be clearer than simply Quantity(Int64), but you know better than me here :)

**Comment by ngam** [comment]
> I don't think there is anything wrong with having vectors of heterogeneous quantities, so showing a warning there would give the wrong impression

This definitely gave me the impression that they're somewhat discouraged (due to performance degradation): https://painterqubits.github.io/Unitful.jl/stable/highlights/#Arrays

**Comment by ngam** [comment]
Anyway, my original issue is resolved. Thank you for the tip about eltype; and as currently designed, Unitful.jl is sufficiently good that no additions are needed!
