### ISSUE TITLE
question / clarification about units in REPL

### ISSUE THREAD

**Issue by ngam** [PainterQubits/Unitful.jl#525]
I noticed that on different machines, I get slightly different behavior in terms of how units are shown. For example:

Old MacOS x86_64 machine:
```
julia> using Unitful

julia> ERF = -2 * u"W/m^2"
-2 W m⁻²
```

Old Linux x86_65 machine:
```
julia> using Unitful

julia> ERF = -2 * u"W/m^2"
-2 W m^-2

julia> a = 5 * u"angstrom"
5 Å
```

I am, of course, talking about `m⁻²` vs `m^-2`. Note how `Å` is printed even in the second case (I thought this might be to do with unicode limitation on one of the machines; I also looked around and a suggestion was to change the locale, but that didn't resolve this). 

I thought I would bring this issue here to seek clarification since users may first face this subtle difference using Unitful.jl (at least I did). Any idea what's causing this change on different machines? Any advice/guidance on how to "fix" it?

As always, thanks a lot!

**Comment by giordano** [comment]
When else fails, read the documentation: https://painterqubits.github.io/Unitful.jl/stable/display/

**Comment by ngam** [comment]
Literally the first line!

Sorry, I promise I tried looking around for this and I somehow totally missed that first line! Or it simply didn't register and I thought it was a deeper issue with this particular device. Hence, I was digging into the whole unicode stuff, and I was so confused why `Å` would work and not `m⁻²`. Thanks for the super speedy response! (Closing!)
