### ISSUE TITLE
documenting constants

### ISSUE THREAD

**Issue by ngam** [PainterQubits/Unitful.jl#526]
Hi again, I saw this issue https://github.com/PainterQubits/Unitful.jl/issues/359#issue-639654890 and I am now curious about documenting these constants. I couldn't find them in the documentation (maybe I am missing something, I searched for [const](http://painterqubits.github.io/Unitful.jl/stable/search/?q=const), [constant](http://painterqubits.github.io/Unitful.jl/stable/search/?q=constant), and [SpeedOfLight](http://painterqubits.github.io/Unitful.jl/stable/search/?q=SpeedOfLight), but I couldn't find anything). 

They are relatively easy to find in the src code:
https://github.com/PainterQubits/Unitful.jl/blob/f9992c08c5917f0cb6402bce26cd0a71a61ceb97/src/pkgdefaults.jl#L343

I am not sure if there is an easy way to produce the documentation for them; if there is, it might be a good idea to activate that. I am happy to help write documentation based on the current constants; perhaps they should be cited as well? 

Thanks a lot for your patience with all my questions and comments. Let me know if this documentation is something you'd be interested in adding.

Copying @giordano.

**Comment by giordano** [comment]
If you want to use physical constant, my biased opinion is that you should look at [`PhysicalConstants.jl`](https://github.com/JuliaPhysics/PhysicalConstants.jl).  Disclaimer: I'm the author.

**Comment by ngam** [comment]
Damn, this Julia ecosystem is truly wild! This is amazing, thanks a lot! I assume that PhysicalConstants.jl has all the constants here and some more, right? I will for sure use it from now on since it is dedicated to that.

One minor curiosity just skimming through them, have you decided not to go with unicode superscripts and subscripts because they are not all readily available in Julia? For example, [`AvogadroConstant` is  `N_A` where usually the `A` is subscript](https://en.wikipedia.org/wiki/Avogadro_constant), but the closest thing to it would be `Nₐ` in Julia, which would be somewhat misleading. I wondered if the available unicode set could be expanded in Julia or if that'd be too much of a hassle...

**Comment by ngam** [comment]
Oh, I also like this reasoning (now I am more consciously reading the first lines!) and it would be another reason not to go full in with the short names of constants:

Each dataset listed below exports by default only the full long names of the constants. Short aliases are provided for convenience, but they are not exported, to avoid polluting the main namespace with dozens of short-named variables. Users can to import the short names of the variables they use most frequently, as shown in the examples above

**Comment by giordano** [comment]
> Damn, this Julia ecosystem is truly wild! This is amazing, thanks a lot! I assume that PhysicalConstants.jl has all the constants here and some more, right? I will for sure use it from now on since it is dedicated to that.

Yes, and they are subtype of `AbstractQuantity` here (which I actually introduced in #204 just for `PhysicalConstants.jl`), so you can reuse all the arithmetic defined in this package.

> One minor curiosity just skimming through them, have you decided not to go with unicode superscripts and subscripts because they are not all readily available in Julia? For example, [`AvogadroConstant` is  `N_A` where usually the `A` is subscript](https://en.wikipedia.org/wiki/Avogadro_constant), but the closest thing to it would be `Nₐ` in Julia, which would be somewhat misleading. I wondered if the available unicode set could be expanded in Julia or if that'd be too much of a hassle...  

Yeah, I did use some Unicode letters (like `α`), but I didn't go full in, also because the superscript/subscript support in Unicode is limited, see https://github.com/stevengj/subsuper-proposal.  For example, is there a subscript infinite symbol for `R_∞`?

**Comment by ngam** [comment]
Makes perfect sense. Thanks a lot, this is very thoughtful (much like the overall Julia ecosystem actually).

> For example, is there a subscript infinite symbol for `R_∞`?

No that I am aware of. And that I think about it, it would be a total mess if one tries to commit all-in to all abbreviations, etc. because different communities would clash over the definitions. So this is definitely a much more coherent approach.
