### ISSUE TITLE
typeof(one(typeof(1u"hr")))

### ISSUE THREAD

**Issue by PharmCat** [PainterQubits/Unitful.jl#554]
Why `typeof(one(typeof(1u"hr")))` is `Int`, not `Quantity{Int64, 𝐓 , Unitful.FreeUnits{(hr,), 𝐓 , nothing}}`?

**Comment by sostock** [comment]
Because `one` returns the multiplicative identity, i.e., a value such that `one(x) * x == x`. Therefore, `one(5u"hr")` cannot return a value with units `hr`, because `1hr * 5hr` is `5 hr^2`, not `5 hr`.

There is a function `oneunit` such that `oneunit(5u"hr") == 1u"hr"`. Maybe you want that one.

**Comment by PharmCat** [comment]
> Because `one` returns the multiplicative identity, i.e., a value such that `one(x) * x == x`. Therefore, `one(5u"hr")` cannot return a value with units `hr`, because `1hr * 5hr` is `5 hr^2`, not `5 hr`.
> 
> There is a function `oneunit` such that `oneunit(5u"hr") == 1u"hr"`. Maybe you want that one.

Thanx! It helps.
