### ISSUE TITLE
Calling `promote_type` on a `Quantity` and a `Real` number will return a type where `zero` is not defined

### ISSUE THREAD

**Issue by singularitti** [PainterQubits/Unitful.jl#616]
Suppose I have two matrices: one has `eltype` of `typeof(1u"m")`, and the other has `eltype` to be `Int`. First, we do a `promote_type`, and get the type `Quantity{Int64}`. And then call `zero` on the type, we will see an `ArgumentError`:

```julia
julia> T = promote_type(typeof(1u"m"), Int)
Quantity{Int64}

ulia> zero(T)
ERROR: ArgumentError: zero(Quantity{Int64}) not defined.
Stacktrace:
 [1] zero(x::Type{Quantity{Int64}})
   @ Unitful ~/.julia/packages/Unitful/W8a8X/src/quantities.jl:389
```

This happened when I was using some people's packages (e.g., [LsqFit.jl](https://github.com/JuliaNLSolvers/LsqFit.jl) and [Einsum.jl](https://github.com/ahwillia/Einsum.jl/blob/d703b8437dbf5a3ea46ad518bb591b2c6dbc6793/src/Einsum.jl#L189)). Is there a way to bypass this? I cannot change other people's code, and I do not want to override `promote_rule` or `zero` for these types to avoid type piracy.

**Comment by sostock** [comment]
I don’t think there is much we can do about this. The behavior of both `promote_type` and `zero` seems correct to me. There is no value that can act as zero-element for both `1m` and `1`.

**Comment by singularitti** [comment]
OK, I will close this issue.
