### ISSUE TITLE
[feat] mutable units

### ISSUE THREAD

**Issue by kunzaatko** [PainterQubits/Unitful.jl#656]
How would I go about defining a mutable unit?
# Usecase
I am creating a package that works with microscopy images. Usually the packages that work with images work with the pixels of the image. In microscopy the pixels have a given size and it would be very beneficial for being explicit in this... That is I would like the user to either be able to use a length unit or the number of pixels. Currently this is implemented as
```julia
function set_pixelsize!(px_size::Unitful.Length)
 @eval @unit px "px" Pixel $px_size false
 return nothing
end
```
which the user can call to be able to use pixels anywhere where a length could be used. However, I would like the user to be able to change the pixel size... However, the second call to the function, does not change the pixel size.

# Questions
- Is there any way to deregister a unit and set it again? (in this case, I do not mind that there wouldn't be precompilation)
- If this is not possible, is there a way to fake this interface by saving a global variable and define my own `@u_str` for `px` and conversion between `px` and length?

**Comment by kunzaatko** [comment]
I see that this could probably be done by using the package [`DynamicQuantities.jl`](https://github.com/SymbolicML/DynamicQuantities.jl). I am at the moment trying to determine the details of this but I think that this specific issue (feature) is not solvable in the scope of this package.

**Comment by cstjean** [comment]
I think this is a situation where one would just multiply by a `2px/mm` conversion factor...

**Comment by kunzaatko** [comment]
Yeah, you're right. That is the best way to do that probably.
