### ISSUE TITLE
Int64 Overflow on Simple Conversion

### ISSUE THREAD

**Issue by ejmeitz** [PainterQubits/Unitful.jl#660]
I am trying to do the following unit conversion:
`uconvert(u"Å * ps^-2", 1.0u"kcal*Å^-1*g^-1")`\
but get this error:
`ERROR: OverflowError: 10000000000000 * 10000000000 overflowed for type Int64`

How can I avoid this? The actual conversion is literally just dividing by 418.4. Is there some way to manually define what this conversion should be?

Similar to #430 #510

**Comment by Socob** [comment]
This was fixed in #648 (present in v1.16.1, but not anymore since v1.16.2).
