### ISSUE TITLE
DimensionError when using updating operator ( .*= ) to multiply a Vector by a Unitful.jl Quantity 

### ISSUE THREAD

**Issue by jmtlawrie** [PainterQubits/Unitful.jl#679]
Hello!

I recently noticed what I think might be an undesirable`Dimension Error` when multiplying a `Vector{T} where T <: Real` by a Unitful `Quantity` using the updating operator.

I thought I should mention it incase the reason why a `DimensionError` is thrown here might have farther reaching implications beyond my present understanding of Unitful.jl's design.

I think that this use of the updating operator is quite unusual, and choosing to perform the same operation without using the updating operator works as (I) expected; so this is an easy solution for anyone else who comes across this.

Minimum working example:
```
using Unitful

a = [1, 2]
b = copy(a)
c = copy(a)

a = a .* 2u"m" # works

b .*= 2u"m" # throws: DimensionError:  and m are not dimensionally compatible.

c .*= 2 # works

d = copy(a) 
d .*= 2u"m" # throws: DimensionError: m and 4 m² are not dimensionally compatible.
```
I had a quick look at the stack trace (see below) and it seems like the multiplication occurs, and then there is a final check whether the values need to be scaled to match the prefix of the unit, at which point the error is thrown.

I'd be interested to hear if anyone can tell me if this is the expected (or desired) behaviour when using this syntax or if this `DimensionError` is an unexpected result.

Thanks for your time and have a nice day!

Joe

----
Stack trace:
```
ERROR: DimensionError:  and s are not dimensionally compatible.
Stacktrace:
  [1] #s103#141
    @ ~/.julia/packages/Unitful/J4AJj/src/conversion.jl:7 [inlined]
  [2] var"#s103#141"(::Any, s::Any, t::Any)
    @ Unitful ./none:0
  [3] (::Core.GeneratedFunctionStub)(::Any, ::Vararg{Any})
    @ Core ./boot.jl:602
  [4] uconvert(a::Unitful.FreeUnits{(), NoDims, nothing}, x::Quantity{Int64, 𝐓, Unitful.FreeUnits{(s,), 𝐓, nothing}})
    @ Unitful ~/.julia/packages/Unitful/J4AJj/src/conversion.jl:72
  [5] convert(#unused#::Type{Int64}, y::Quantity{Int64, 𝐓, Unitful.FreeUnits{(s,), 𝐓, nothing}})
    @ Unitful ~/.julia/packages/Unitful/J4AJj/src/conversion.jl:139
  [6] setindex!
    @ ./array.jl:969 [inlined]
  [7] macro expansion
    @ ./broadcast.jl:974 [inlined]
  [8] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [9] copyto!
    @ ./broadcast.jl:973 [inlined]
 [10] copyto!
    @ ./broadcast.jl:926 [inlined]
 [11] materialize!
    @ ./broadcast.jl:884 [inlined]
 [12] materialize!(dest::Vector{Int64}, bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1}, Nothing, typeof(*), Tuple{Vector{Int64}, Quantity{Int64, 𝐓, Unitful.FreeUnits{(s,), 𝐓, nothing}}}})
    @ Base.Broadcast ./broadcast.jl:881
 [13] top-level scope
```

Version Information:
```
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (x86_64-apple-darwin22.4.0)
  CPU: 4 × Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, broadwell)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 

(@v1.9) pkg> st Unitful
Status `~/.julia/environments/v1.9/Project.toml`
  [1986cc42] Unitful v1.17.0
```
----

**Comment by cstjean** [comment]
It's the expected behaviour. `.=` cannot change the type of the left-hand-side, it's a mutating operator. Therefore if you have a Vector of Int, it can't become a Vector of meters, which is what would be needed for `.=` operations to work.

If you're worried about allocation, I think that you can use `reinterpret` to achieve something similar to `.*=`, but I wouldn't mess with this unless I was sure that performance is a problem. I'd just use `*=`

**Comment by jmtlawrie** [comment]
@cstjean thank you for explaining, I was unaware of this characteristic of the mutating operators and why the following snippet returns `InexactError: Int64(2.5)`.

I'll close this issue now, thank you!

```
a = [1, 2]
a .*= 2.5
```
