### ISSUE TITLE
Converting to dBSPL from Pa gives incorrect answer

### ISSUE THREAD

**Issue by ubertakter** [PainterQubits/Unitful.jl#683]
Converting pressure level to sound pressure level gives an incorrect result. Example:

`julia> uconvertrp(u"dBSPL", 35u"Pa")`
`124.86076097372589 dBSPL`

The expected answer is `28.750252691799393`.

I skimmed the source code but it was not immediately apparent how this value is calculated.

**Comment by sostock** [comment]
The result seems correct to me. `dBSPL` uses a reference pressure of 20 μPa, which according to [Wikipedia](https://en.wikipedia.org/wiki/Sound_pressure#Sound_pressure_level) is commonly used for sound pressure in air.

Using a reference sound pressure of 20 μPa, we get
```julia
julia> 20 * log10(35u"Pa" / 20u"μPa")
124.86076097372589
```
Why do you expect to get `28.750252691799393`?

**Comment by ubertakter** [comment]
> The result seems correct to me. `dBSPL` uses a reference pressure of 20 μPa, which according to [Wikipedia](https://en.wikipedia.org/wiki/Sound_pressure#Sound_pressure_level) is commonly used for sound pressure in air.
> 
> Using a reference sound pressure of 20 μPa, we get
> 
> ```julia
> julia> 20 * log10(35u"Pa" / 20u"μPa")
> 124.86076097372589
> ```
> 
> Why do you expect to get `28.750252691799393`?

Yeah, no, you are correct. That's what I get for trying to work things out at the end of the day. 

I work with explosions a lot, where the threshold for injury (in terms of pressure) is much higher than the threshold for injury due to noise. Humans is weird.
