### ISSUE TITLE
unit(Quantity) should be an error

### ISSUE THREAD

**Issue by cstjean** [PainterQubits/Unitful.jl#734]
`unit(Quantity)` currently returns `Unitful.NoUnits`. But that's wrong, right? "Units are unknown" is not the same as "No units". Concretely, we hit:

```julia
julia> unit(eltype(ifelse.([true, false], [1.0V, 2.0V], [3.0mV, 4.0mV])))
    # no unit
```

Incidentally, `eltype(Any[2, 3])` returns `Any` which at first glance might look similar, but of course `2 isa Any` is true, so the answer is correct in some sense, whereas `1.0V` is _not_ unitless.

Hence, it should be an error. Or perhaps it could return `nothing`.

**Comment by sostock** [comment]
#524

I would prefer throwing an error over returning `nothing`.
