### ISSUE TITLE
Is one of a quantity expected to return the backing type? 

### ISSUE THREAD

**Issue by prittjam** [PainterQubits/Unitful.jl#748]
```
using Unitful
a = 1.0u"m"
one(eltype(a))
```

I would expect it to return one unit, but it just returns 1.0.

**Comment by sostock** [comment]
The current behavior is correct, since `one` returns the multiplicative identity element, i.e., `x * one(x) == x`.

**Comment by prittjam** [comment]
whats the best way to get the quantity one? e.g., 

```
one(eltype(x))*Unitful.unit(x[1])
````
